### ISSUE TITLE
2 x dezelfde tijdrovende berekening bij output option table / export aggrgation

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#116]
Bij tijdrovende queries is het jammer dat amcat eerst de tijd neemt om de table op het scherm te produceren, maar dan hetzelfde nog een keer doet bij export aggregation van dezelfde table naar een uitvoerbestand, 

Misschien kan aan export table een derde optie worden naast table en graph worden toegevoegd, nl. export table, met een dubbele uitvoer: zowel naar een table op het scherm als naar een table in een exportbestand naar keuze (csv, xlsx, etc)

**Comment by martijnbastiaan** [comment]
I propose doing the following:

1. A QueryAction may issue a X-QUERY-CACHE header to the browser (UUID)
2. The browser must..
  1. send this UUID *if* "nothing" has changed (default: output_type) on next query
  2. delete UUID *if* something significantly changes (default: anything but output_type)
3. The server may use the UUID to fetch old results from memcached

I think this has several advantages over other mechanisms:

1. Cache keys are stored in the browser, which means an F5 will always get you fresh results even in face of bugs.
2. Ideally, presentation and data are strictly decoupled (so you could just cache *any action*), but this isn't true in reality due to various reasons. Using this strategy, the Action implementation judges what is cachable. 
3. It is simple, no real cache invalidation issues exist. Two separate users will never get the same (cached) results.

**Comment by martijnbastiaan** [comment]
(19:58:41) Wouter: misschien hash van input form met session id?
(19:59:06) Martijn: Dat zou nog wel kunnen
[..]
(19:59:54) Wouter: en een 5 of 10 minuten timeout?
(19:59:59) Wouter: want zo vaak verandert data nu ook weer niet
(20:00:58) Martijn: Ja, misschien gewoon langer met een melding
(20:01:25) Martijn: "You are viewing cached [maar dan met een beter worod] results. Click here to clear it."
[..]
(20:03:18) Martijn: Doen?
[..]
(20:04:51) Wouter: ik zeg: make it so

**Comment by martijnbastiaan** [comment]
Almost implemented caching:

- [X] Implemented SelectionForm.get_hash() (https://github.com/amcat/amcat/commit/8cfceddd4b7884f20d6edbf8854437849c247ebb)
- [X] Implemented QueryAction.{set,get}_cache() (https://github.com/amcat/amcat/commit/7c65fff23d3821ca5772052217ecde5968f0edec)
- [X]  Added caching to aggregators (https://github.com/amcat/amcat/commit/50a0542ed59d27f54bd0e0f5e3099c875fe36854)
- [ ] Add 'clear cache' button to GUI

**Comment by martijnbastiaan** [comment]
785 dagen later.. fixed!

https://gfycat.com/ShadowyInexperiencedGoa
