### ISSUE TITLE
Earlier changes to code labels in amcat.nl do not show in preview.amcat.nl

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#421]
Months ago, I made changes to the code labels in a codebook in amcat.nl, for example
![code labels 1](https://cloud.githubusercontent.com/assets/6417728/10909438/9704e3ba-8239-11e5-8b65-a169e89f4825.png)

However, preview.amcat.nl shows the same codebook without the changes
![code labels 2](https://cloud.githubusercontent.com/assets/6417728/10909451/a842d272-8239-11e5-9198-69afa7a2af89.png)

It seems as if in preview, the code seems to have both an old an a new label; when I want to change the label, it looks like this -- the new label is there, but preview shows the old one
![code labels 3](https://cloud.githubusercontent.com/assets/6417728/10909507/17e1d376-823a-11e5-86a1-daabcc55253a.png)

However, in amcat.nl, the same interface for changing the label only shows only one label, the new one
![code labels 4](https://cloud.githubusercontent.com/assets/6417728/10909530/39f120ac-823a-11e5-9560-e0d745f6625d.png)

Is there a way to make preview show the new labels, or do I have to change them manually?

**Comment by vanatteveldt** [comment]
This is a feature :-). It is caused by #348: 3.4 has a default label that is not attached to a particular language, and this label is used by default in places where otherwise you had to specify a language as well. It is also more efficient as they can be loaded directly independent of the language, especially in cases where some codes don't have a label for some languages.

You are caught in between here, since the default labels were loaded from the first label in the old system, but the old system doesn't know about these labels so also can't show or change them. The workaround would be to edit the label again in 3.4. You can edit the default label like in windows Explorer by clicking on the code in the tree or with the top value in the dialog (you don't need the 'labels' dialog anymore unless you specifically need to work with multiple languages). 

If you have  a lot of codes we can also do this automatically, just give me a shout.
