### ISSUE TITLE
Option to group media in query

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#430]
In codingjob export you can aggregate the medium, e.g. to work with media groups or to correct errors. It would be nice if we can do this in query as well.

(Filing under bzk, even though it is probably generic to query)

**Comment by vanatteveldt** [comment]
I think the option should be interpreted broadly: any field should be "groupable", especially if #440 is implemented.

[And in the future I want interactive charts, i.e. http://www.highcharts.com/demo/column-drilldown, allowing the user to drill down from the group to the invidual items again, but that would require sending the grouping to js rather than doing it server side]

**Comment by martijnbastiaan** [comment]
>  but that would require sending the grouping to js rather than doing it server side

Just add a tertiary aggregation I suppose. This is already implemented (more or less) on the server side, only the rendering would need attention.

> I think the option should be interpreted broadly: any field should be "groupable", especially if #440 is implemented

Agree, but let's make a separate issue for that. I'm going to close this one as soon as medium aggregation is implemented.

**Comment by martijnbastiaan** [comment]
This has been implemented in master:

- Backend: https://github.com/amcat/amcat/commit/4fed533aa07db9157f92033ff2ffc7bec49938d5
- Frontend: https://github.com/amcat/amcat/commit/423aa7cc4d4e9d7ac45e314489b5f28428c9ac15
