### ISSUE TITLE
Cannot sample articleset

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#490]
I tried to draw a sample from an articleset
![sample1](https://cloud.githubusercontent.com/assets/6417728/13771977/df2d8618-ea91-11e5-949d-250156c0e754.png)

But AmCAT showed an error
![sample2](https://cloud.githubusercontent.com/assets/6417728/13771992/f3a3cb5c-ea91-11e5-96ce-46e8a9ca73e5.png)

(perhaps it is relevant that the articleset used for the sample was linked from another project)

In version 3.3, AmCAT appeared to create the sample for the same articleset without problems
![sample3](https://cloud.githubusercontent.com/assets/6417728/13772017/1e7792aa-ea92-11e5-8a1d-495ede317b7b.png)

But the sample never showed up in the list of articleset (also not under 'archived sets')
![sample4](https://cloud.githubusercontent.com/assets/6417728/13772036/34533e76-ea92-11e5-8b9c-e526c4293d02.png)

(I tried refreshing it to see if that would work, hence the 'ArticlesetRefreshView' message in the previous screenshot, but that didn't solve the issue)

**Comment by CJStuart** [comment]
The sample sets appear to be made in the original project, rather than the project that it's linked from: 

The articleset isn't found in the project that i'm working on:

![image](https://cloud.githubusercontent.com/assets/2796609/13780642/a1fca1fa-eac0-11e5-9e48-2538e7e99f6d.png)

however, the articleset does exist in the project that the original articleset belongs to:

![image](https://cloud.githubusercontent.com/assets/2796609/13780699/df372d1a-eac0-11e5-86d1-d88ed0f7848e.png)
