### ISSUE TITLE
Maximum length query

### ISSUE THREAD

**Issue by mse234** [amcat/amcat#514]
I found any problems with testing my query from the McDonald and Loughran word list. I would like to use a query to test the negative sentiment in the news. This query contains a lot of words (over 4000) and AMCAT gave an undefined error. I found that AMCAT is only able to search for query's with a maximum length of 1023 words. Is there any chance to improve the maximum length? The current length is not long enough for sentiment analysis..

**Comment by vanatteveldt** [comment]
The problem is that elasticsearch can have difficulty with long and complex queries. While sentiment is generally not very complex, it can be if you want sentiment within a certain distance of actors. So, the 1024 (which is actually probably on the high side) is there to prevent one user from slowing / disabling search for other users. 

We will probably add a special "sentiment analysis" option, which allows for very long lists but does not allow complex queries, but in the meantime you have three options:

1) Install your own server (it's open source!).
2) Split your query into smaller sets.
3) Use R and the corpustolls and semnet packages.

**Comment by vanatteveldt** [comment]
@mse234 this might help you get started with the imho best option, namely using R and semnet: http://vanatteveldt.com/semnet-sentiment/
