### ISSUE TITLE
Firefox js problem

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#562]
Ilse Ploegmakers geeft aan dat bij haar in Firefox  de query pagina niet goed laadt, de query knop blijft disabled en de 3 datumvelden die normaal verdwijnen worden getoond. 

Max, firefox versie 50.0

Console log:

```
function jQuery()  poll.js:186:5
Error: Script error for "highcharts.heatmap", needed by: query/renderers
http://requirejs.org/docs/errors.html#scripterror  require.js:168:17
        makeError https://amcat.nl/media/static/components/requirejs/require.js:168:17
        newContext/context.onScriptError https://amcat.nl/media/static/components/requirejs/require.js:1735:36
```

**Comment by CJStuart** [comment]
Dit lijkt me een probleem met een adblocker. De filterlijst EasyPrivacy
bevat een entry voor alles genaamd heatmap.js.

In de master bestaat hier al een waarschuwingsbericht voor (zie #508).

De vraag is of we hier een workaround voor willen gebruiken, of gewoon
adblockers de schuld geven.

On 28 Nov 2016 5:57 p.m., "Wouter van Atteveldt" <notifications@github.com>
wrote:

Assigned #562 <https://github.com/amcat/amcat/issues/562> to @CJStuart
<https://github.com/CJStuart>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/amcat/amcat/issues/562#event-873940604>, or mute the
thread

**Comment by martijnbastiaan** [comment]
Wij willen hiervoor gewoon de adblocker de schuld geven. Kunnen we in de toekomst nog advertenties inbouwen ook :^).
