### ISSUE TITLE
uploader performance

### ISSUE THREAD

**Issue by kasperwelbers** [amcat/amcat#592]
I'm currently uploading a lot of lexisnexis data locally, and was surprised about how bad my laptop could handle this. On a 4 core 8 gb laptop, uploading a batch of 20,000 lexisnexis articles would often freeze up everything else for about 20 min. 

My suspect is the (somewhat new) script that first runs through all of the data to see what fields there are. I appreciate the convenience of this, but I fear that it might not handle working through many batches efficiently. Does it currently keep all data in memory till after the user specifies what fields to use? 

In any case, given how much it pisses of my laptop, it might be good to identify the bottleneck.

**Comment by CJStuart** [comment]
The parser only keeps one single file (or one single zip entry) in memory at a given time, so unless a zip archive contains extremely large files (i.e. hundreds of megabytes), that shouldn't be the issue. On my machine, it takes about a minute to load an entire set of 30 000 articles.

I did, however, run into performance problems when an incorrect encoding is selected. In that case, the Dateparser library tries to parse dates such as "1 SÃ¸ndag 17. Juli 2016", but fails because of the improper encoding, and takes a long time before it gives up. I ran a cProfiler test using latin-1 encoding on one single ~1MB utf-8 encoded file containing 200 articles. This took over a minute to run, and
 60.985 of the 61.128 seconds were spent in the dateparser.parse function:

    ncalls  tottime  percall  cumtime  percall filename:lineno(function)

        2    0.000    0.000   61.128   30.564 upload.py:236(_get_files)
      ...
      544    0.002    0.000   61.016    0.112 lexisnexis.py:206(_is_date)
      ...
      244    0.001    0.000   60.985    0.250 __init__.py:9(parse)

The full output: https://gist.github.com/CJStuart/fc1613aaf55fb8c43765f8533d2d4a49

On a data set of 20000 articles, this would take hours to run. The same problem would likely occur with languages or date formats that are not supported by Dateparser.

I'm not sure how this can be resolved, because we're relying on the dateparser library to figure out whether something is a date or not, and considering the wide range of languages and formats it supports, we don't really have another choice.

**Comment by vanatteveldt** [comment]
One option could be to revert back to our own dateparser function (https://github.com/amcat/amcat/blob/release-3.4/amcat/tools/toolkit.py#L346-L511). We could spin it off as a separate library. 

Alternatively, we could try to fix the dateparser, or at least log an issue with them. It's this one, right? https://github.com/scrapinghub/dateparser/issues

**Comment by kasperwelbers** [comment]
Excellent identification of the bottleneck :). My lexisnexis data contained many different media, from different countries, so the date parsing could very well have been the culprit.

**Comment by kasperwelbers** [comment]
By the way, regarding Wouter's idea of reverting back to the date parser in toolkit. Perhaps a compromise is best, where the default is to use the parser in toolkit, but users can select dateparser in the upload menu. The main advantage would be that dateparser also deals with many different languages.

**Comment by martijnbastiaan** [comment]
Couldn't we just stop parsing after failing to parse some percentage of dates? We could do a sliding window: if we just failed parsing the date of article N, we look at the parse results of [N-100, N-99, ..., N] and determine if we're below some threshold. We could then show the user which dates failed (and for "1 SÃ¸ndag 17. Juli 2016" it should be pretty obvious what's going on).

**Comment by CJStuart** [comment]
Alternatively we could try to reduce dateparser's language pool according to the language of the article. As I understand it, dates in LexisNexis occur in either the metadata language, or the article's language (NB: I'm not 100% sure if this is true). Both are easy to figure out, if the contains a language tag. The language tag is given in the metadata language (e.g. "language" for english, "langue" for french), and the language tag contains both the language's name in the metadata language, as well its native name (e.g. "Danish; Dansk").
 
I made a quick draft in the branch feature_lexisnexis_dateparser_languages (2e25fe8ce60ba0f0700d7327c88a633192dacd3c)
My current approach is:

1. register the languages that dateparser recognizes in a dict, under two aliases: its fullname (in English), and its shortname.
2. if the article has a "language" tag, pass this as well as the file's metadata language to read_date as a tuple (currently something like `("danish", "dansk", "en")`). Otherwise, pass `None` as the language, and fall back to normal operation.
3. In read_date, do a lookup in the language dict, instantiate a custom DateParser instance, and pass it an AutoDetectLanguage instance with the limited language pool. If no language pool is available, use the normal dateparse.parse function. 
4. Parse the date as usual.

The performance increase is significant, running the same cProfile command only takes 2 seconds. 

A few problems with this: 
* Only works if the language tag is given.
* I'm currently not translating languages from the file language to English, so only files with English metadata can be parsed using this method. It should be possible to figure out which language the metadata is by matching the language tag's name (e.g. "langue", "sprache", etc.), but translating the language is a bit more difficult. Possibly the native name of the language should be registered in the language dict in step 1

Are there any other pitfalls that should be considered when doing this?

**Comment by martijnbastiaan** [comment]
You might be able to solve your problems with:

```bash
sudo apt install python3-guess-language
```

:-). I've used it on [this](http://nos.nl/artikel/2170332-wat-zou-een-nieuwe-wegenbelasting-jou-gaan-kosten.html) article, which seems to work fine. Each run takes about 9 ms, which should be fine?

**Comment by vanatteveldt** [comment]
I think this was solved by a combination of guessing the language and a bugfix pushed to the dateparser, right?
