### ISSUE TITLE
Can't upload LexisNexis files into AmCAT

### ISSUE THREAD

**Issue by bartlund** [amcat/amcat#603]
Dear all,

I have downloaded a number of TXT. files from LexisNexis and would like to upload them in AmCAT. Unfortunately however, some files can be uploaded while others cannot. I receive a 'Polling failed. Refresh?' notification. I attach one of the non-working files - is someone able to tell me if there is something wrong in this file? Many thanks in advance!

Best wishes,
Bart

[ABC EU 1985-2000.TXT](https://github.com/amcat/amcat/files/1040804/ABC.EU.1985-2000.TXT)

**Comment by vanatteveldt** [comment]
@CJStuart  Hey Christian, could you have a look at this? Cheers!

**Comment by bartlund** [comment]
Thanks!

**Comment by CJStuart** [comment]
Hi Bart,

The articles contain a lot of very strange problems. First of, in a couple of articles every last word of every field is repeated multiple times. For example:

```
                              138 of 380 DOCUMENTS

               $% Agence France Presse -- English english english

                  October 24, 1997 1997 1997 24:03 GMT gmt gmt

Hashimoto criticizes EU greenhouse gas proposal proposal proposal

SECTION: International news news news

LENGTH: 177 words words words

DATELINE: TOKYO, Oct 24 24 24
...
```
Here, the date parser fails to parse the date line `October 24, 1997 1997 1997 24:03 GMT gmt gmt`, which makes sense. 

Another problem is that many given dates are otherwise invalid or not parseable:

* some date lines contain the timezone indication "Eastern Time", which the date parser doesn't seem to  like. 
* some dates suffixed by "AM cycle", "BC cycle" or "PM cycle", 
* a few dates contain the text "Friday R"
* a couple of timestamps give a time of day greater than 24:00

Furthermore, some articles seem to miss the source line in the header, which also trips up the parser.

I've fixed these issues in the file you included, which works well now: 
[ABC.EU.1985-2000-modified.TXT](https://github.com/amcat/amcat/files/1065308/ABC.EU.1985-2000-modified.TXT)


-- Christian

**Comment by bartlund** [comment]
Dear Christian,

Thank you so much for helping us out with this!! Strange that the LexisNexis txt. files include such errors, but at least now we know what the problems are. This is of great help to us!

Thanks again and warm regards,
Bart
